### ISSUE TITLE
ssh或telnet扫描模式下如何指定一个特定的用户名和密码组合进行破解？

### ISSUE THREAD

**Issue by CMCCAdmin** [0xHJK/TotalPass#1]
ssh或telnet扫描模式下如何指定一个特定的用户名和密码组合进行破解？

**Comment by 0xHJK** [comment]
可以修改payloads/ssh/ssh.yml中的用户名和密码，或者使用`-d`指定自己的密码字典

**Comment by 0xHJK** [comment]
telnet 也类似
